version: '3.9'

services:
  activemq:
    image: apache/activemq-classic:6.1.1
    container_name: activemq-st02
    restart: unless-stopped
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNTS: "true"
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
